// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xuyang/code/react-ui/node_modules/.pnpm/dumi@2.1.10_zula6vjvt3wdocc4mwcxqa6nzi/node_modules/dumi/theme-default/slots/HeadeExtra/index.js';
